//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynacomAutoTaskWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynaUsers
    {
        public string UserGUID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public byte[] Password { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> FirstLogin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> LogCount { get; set; }
        public Nullable<int> MessengerStatus { get; set; }
        public byte[] Avatar { get; set; }
        public string HiddenUsers { get; set; }
        public string AwayMessages { get; set; }
        public string Version { get; set; }
        public string FrameworkVersion { get; set; }
    }
}
