//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynacomAutoTaskWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynaAutoTasks
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
        public string Category { get; set; }
        public Nullable<int> RecordHandling { get; set; }
        public Nullable<bool> AvailableToAutoMan { get; set; }
        public string DataObjectID { get; set; }
        public string Actions { get; set; }
        public string Owner { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Query { get; set; }
        public Nullable<int> ProcessRecords { get; set; }
        public Nullable<double> LastRun { get; set; }
        public string Recurrence { get; set; }
        public Nullable<bool> ProcessAll { get; set; }
        public Nullable<bool> ProcessFailedRows { get; set; }
        public Nullable<bool> SkipRowSelection { get; set; }
        public Nullable<System.DateTime> BaseTimeStamp { get; set; }
        public string ShortDescr { get; set; }
    }
}
